### ISSUE TITLE
Can't unpack new IPF files from krOBT

### ISSUE THREAD

**Issue by xeldarith** [TwoLaid/treeofsavior-tools#1]
I can't seem to unpack new ipf file from kOBT.

Here's the error:
```
Could not unpack ability_Doppelsoeldner.ies
{'datafile': None, '_filename': 'ability_Doppelsoeldner.ies', '_archivename': 'ies_ability.ipf', '_unknown1': None, '_archivename_length': 15, '_compressed_length': 645, '_filename_length': 26, '_data_offset': 55910, '_uncompressed_length':  5445, '_crc': 1143676072}
Error -3 while decompressing data: invalid distance too far back
Traceback (most recent call last):
  File "ipf.py", line 430, in <module>
    ipf.extract_all(args.directory or '.')
  File "ipf.py", line 312, in extract_all
    print(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

This is the ipf file:
[ies_ability.txt (rename to .ipf)](https://github.com/TwoLaid/treeofsavior-tools/files/72369/ies_ability.txt)

Nevertheless, it's a simple & great tool.
Thanks.

**Comment by Spl3en** [comment]
[IPFUnpacker](https://github.com/r1emu/IPFUnpacker) implements an algorithm for decrypting the IPFs.

**Comment by xeldarith** [comment]
oh right.
Thanks.
